import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="backgroundImage">
        <header className="bg-black p-4"> 
          <Navbar />
        </header>
        {children}
        <footer className="absolute inset-x-0 bottom-0 bg-black p-4">
          <Footer />
        </footer>
      </body>
    </html>
  )
}
