import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head >
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      </head>
      <body className="backgroundImage flex flex-col min-h-screen">
        <header className="bg-black p-4"> 
          <Navbar />
        </header>
        <main className="flex-grow">
        {children}
        </main>
        <footer className="bg-black p-4">
          <Footer />
        </footer>
      </body>
    </html>
  )
}
